name: Pulumi Preview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pulumi-preview:
    if: github.actor == 'MauDantas'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH
        env:
          PULUMI_SKIP_UPDATE_CHECK: "true"
      
      - name: Verify and Initialize DYI Backend
        env:
          SPACES_ENDPOINT_URL: ${{ secrets.SPACES_ENDPOINT_URL }}
        shell: bash
        run: |
          # Use aws s3api head-object to reliably check if the file exists.
          if aws s3api head-object \
            --bucket ${{ secrets.BUCKET_NAME }} \
            --key pulumi-state/.pulumi/meta.yaml \
            --endpoint-url "$SPACES_ENDPOINT_URL" > /dev/null 2>&1
          then
            echo "âœ… Pulumi Remote Backend (meta.yaml) found."
          else
            echo "The remote backend config is not done. Proceeding to initialize."
            # If 'meta.yaml' is missing, you can add initialization steps here,
            # or the rest of your workflow (e.g., 'pulumi login') will handle it.
          fi
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_S3_FORCE_PATH_STYLE: true

#      - name: Configure Pulumi stack values
#        env:
#          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
#        run: |
#          pulumi config set region ${{ secrets.DIGITAL_OCEAN_REGION }} --stack staging
#          pulumi config set vpc:env staging --stack staging
#          pulumi config set vpc:ip_range ${{ secrets.DIGITAL_PRIVATE_NETWORK }} --stack staging
#          pulumi config set security:allowed_ssh_cidr ${{ secrets.DIGITAL_PRIVATE_NETWORK }} --stack staging
#          pulumi config set digitalocean:token --secret ${{ secrets.DIGITAL_OCEAN_TOKEN }} --stack staging
#
#      - name: Pulumi Preview
#        run: |
#          poetry run pulumi preview --stack staging
#        env:
#          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
#
#      - name: Sync Pulumi state to Agnostic S3
#        run: |
#          aws s3 cp $HOME/.pulumi/stacks/ s3://pulumi-infrastructure/states/ \
#            --recursive --endpoint-url $AWS_ENDPOINT_URL_S3
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          AWS_S3_FORCE_PATH_STYLE: true
#          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
